#!/bin/bash

level() {
  brightnessctl | grep -o '[0-9]\+%' | grep -o '[0-9]\+'
}

[[ $1 == "UP" ]] && brightnessctl s 10%+
[[ $1 == "DOWN" ]] && brightnessctl s 10%-


if [[ $(level) == 0 ]]; then
  brightnessctl s 1%
fi

level
