#!/bin/sh
[[ "$1" == "HDMI" ]] && xrandr --output eDP1 --off --output DP1 --off --output DP2 --off --output HDMI1 --mode 2560x1440 --pos 0x0 --rotate normal --output HDMI2 --off --output VIRTUAL1 --off
[[ "$1" == "EDPI" ]] && xrandr --output eDP1 --mode 1920x1080 --pos 0x0 --rotate normal --output DP1 --off --output DP2 --off --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off
[[ "$1" == "HDMIABOVE" ]] && xrandr --output eDP1 --primary --mode 1920x1080 --below HDMI1 --output DP1 --off --output DP2 --off --output HDMI1 --mode 2560x1440 --pos 0x0 --rotate normal --output HDMI2 --off --output VIRTUAL1 --off
[[ "$1" == "HDMIRIGHT" ]] && xrandr --output eDP1 --primary --mode 1920x1080 --pos 0x706 --rotate normal --output DP1 --off --output DP2 --off --output HDMI1 --mode 2560x1440 --pos 1920x0 --rotate normal --output HDMI2 --off --output VIRTUAL1 --off
