#!/bin/bash

if [[ $1 == "off" ]]; then
    printf "blacklist nouveau\nblacklist nvidia\n" > /etc/modprobe.d/nographics.conf
    printf "acpi_call" > /etc/modules-load.d/acpi_call.conf
    rm /etc/X11/xorg.conf
    pacman -Rs nvidia nvidia-utils
    printf "Remove the following lines from .xinitrc and then reboot.\nxrandr --setprovideroutputsource modesetting NVIDIA-0\nxrandr --auto\nxrandr --dpi 85\n"
elif [[ $1 == "on" ]]; then
    printf "" > /etc/modprobe.d/nographics.conf
    printf "" > /etc/modules-load.d/acpi_call.conf
    pacman -S nvidia
    cat <<END > /etc/X11/xorg.conf
Section "Module"
    Load "modesetting"
EndSection

Section "Device"
    Identifier "nvidia"
    Driver "nvidia"
    BusID "1:0:0"
    Option "AllowEmptyInitialConfiguration"
EndSection
END
    printf "Add the following lines to .xinitrc and then reboot.\nxrandr --setprovideroutputsource modesetting NVIDIA-0\nxrandr --auto\nxrandr --dpi 85\n"
else
    echo "Arguement must be provided: on/off"
fi
