#!/bin/bash

sink=$(pactl list sinks | grep 'Sink' | grep -o '[0-9]*' | tail -n1)

[[ "$1" == "UP" ]] && pactl set-sink-volume "$sink" +2%
[[ "$1" == "DOWN" ]] && pactl set-sink-volume "$sink" -2%
[[ "$1" == "MUTE" ]] && pactl set-sink-mute "$sink" toggle

volume=$(pactl list sinks | grep 'Volume.*\(,\|mono\).*' | tail -n1 | awk '{print $5}')
mute=$(pactl list sinks | grep 'Mute' | tail -n1 | awk '{print $2}')
echo "$volume"

