alias pip="pip3"
alias python="python3"
alias p="python3"
alias pe="pipenv"

alias tmux="TERM=screen-256color-bce tmux"
alias icat="kitty +kitten icat"
alias weather="curl http://wttr.in/"

alias gg="git log --graph --abbrev-commit --branches --decorate --format=format:'%C(bold blue)%h%C(reset) %x09%C(bold white)%<(70,trunc)%s%C(reset) %C(magenta)- %an %C(reset) %C(cyan)%ai%C(reset) %C(auto)%d%C(reset)'"
alias yg="yadm log --graph --abbrev-commit --branches --decorate --format=format:'%C(bold blue)%h%C(reset) %x09%C(bold white)%<(70,trunc)%s%C(reset) %C(magenta)- %an %C(reset) %C(cyan)%ai%C(reset) %C(auto)%d%C(reset)'"
alias gs="git status"
alias gp="git push"
alias ga="git add"
alias gc="git commit"
alias gco="git checkout"
alias gd="git diff"
alias gr="git rebase"
alias gl="git pull"
alias gb="git branch"
alias gt="cd \$(git rev-parse --show-toplevel)"
alias gh="git stash"
alias ys="yadm status"
alias yp="yadm push"
alias ya="yadm add"
alias yc="yadm commit"
alias yco="yadm checkout"
alias ym="yadm checkout master"
alias yar="yadm checkout arch"
alias yd="yadm diff"
alias yr="yadm rebase"
alias yl="yadm pull"

alias v="nvim"
alias za="zathura"
alias sv="sudo edit"
alias l="tree -DhvC -L 1"
alias t="tree -DhvC"
alias tl="tree -DhvC -L"
alias r="rg --max-depth=10 --hidden --pretty --follow"
alias x="z -I"
alias uuid="python -c \"import uuid; print(str(uuid.uuid4()));\""

alias kc="kubectl"
alias mk="minikube"
alias d="docker"
alias dc="docker-compose"

alias sa="sudo aura"
alias sc="sudo systemctl"
[[ -f "$HOME/.config/system/local.alias.sh" ]] && source "$HOME/.config/system/local.alias.sh"
