name:                myXmonad
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/rcarriga/myXmonad#readme
license:             BSD3
author:              R칩n치n Carrigan
maintainer:          ronan.carrigan@gmail.com
copyright:           2019 R칩n치n Carrigan
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - xmonad
  - xmonad-contrib
  - containers
  - text
  - X11
  - ghc

executables:
  xmonad:
    source-dirs:      src
    main:             xmonad.hs
