#!/bin/zsh

if [[ -d $1 ]]; then
  tree -DhvC -L 1 $1
elif [[ -n $(file -b $1 | grep 'text' ) ]]; then
  bat -r :"$LINES" "$1" --color always
elif [[ -n $(file -b $1 | grep 'Zip' ) ]]; then
  unzip -l $1
elif [[ -n $(file -b $1 | grep 'gzip compressed data' ) ]]; then
  tar -tf $1
else
  file $1
fi
