name:                myXmonad
version:             0.1.0.0
homepage:            https://github.com/rcarriga/dotfiles
author:              R칩n치n Carrigan
maintainer:          ronan.carrigan@gmail.com
copyright:           2020 R칩n치n Carrigan

dependencies:
  - base >= 4.7 && < 5
  - xmonad
  - xmonad-contrib
  - containers
  - text
  - X11
  - ghc

executables:
  xmonad:
    source-dirs:      src
    main:             xmonad.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
