#!/bin/bash

sink=$(pactl list sinks | grep 'Sink' | grep -o '[0-9]*' | tail -n1)

[[ "$1" == "UP" ]] && pactl set-sink-volume "$sink" +2% && pkill -SIGRTMIN+1 i3blocks
[[ "$1" == "DOWN" ]] && pactl set-sink-volume "$sink" -2% && pkill -SIGRTMIN+1 i3blocks 

volume=$(pactl list sinks | grep 'Volume.*,.*' | tail -n1 | awk '{print $5}')
echo "  VOL:$volume "
